import * as cheerio from 'cheerio';
import { LlmsDocument, LlmsGenerateOptions, LlmsPage, LlmsSourcePage } from './types.js';

interface Frontmatter {
  title?: string;
  description?: string;
  summary?: string;
}

const SECTION_ORDER = ['Docs', 'API', 'Product', 'Blog', 'Site', 'Optional'];

export function buildLlmsDocument(
  sources: LlmsSourcePage[],
  options: LlmsGenerateOptions
): LlmsDocument {
  const pages = dedupePages(
    sources
      .map((source) => extractLlmsPage(source))
      .filter((page) => page.title && page.description)
  )
    .sort((a, b) => {
      const sectionDelta = sectionRank(a.section) - sectionRank(b.section);
      return sectionDelta === 0 ? a.url.localeCompare(b.url) : sectionDelta;
    })
    .slice(0, Math.max(1, options.maxLinks));

  const siteName = options.siteName ?? inferSiteName(options.site ?? pages[0]?.url);
  const summary =
    options.summary ??
    pages[0]?.description ??
    `${siteName} provides curated website content for humans and AI agents.`;

  return {
    siteName,
    summary,
    details: `Generated by AnswerLint from ${pages.length} deterministic content source${
      pages.length === 1 ? '' : 's'
    }.`,
    pages,
  };
}

function dedupePages(pages: LlmsPage[]): LlmsPage[] {
  const byUrl = new Map<string, LlmsPage>();

  for (const page of pages) {
    const existing = byUrl.get(page.url);
    if (!existing || pageQuality(page) > pageQuality(existing)) {
      byUrl.set(page.url, page);
    }
  }

  return [...byUrl.values()];
}

function pageQuality(page: LlmsPage): number {
  const markdownBonus = /\.(md|markdown|mdx)$/i.test(page.sourcePath ?? '') ? 1000 : 0;
  return markdownBonus + page.description.length + Math.min(page.text.length, 500);
}

function extractLlmsPage(source: LlmsSourcePage): LlmsPage {
  const frontmatter = parseFrontmatter(source.raw);
  const html = source.html ?? source.raw;
  const $ = cheerio.load(html);

  $('script, style, noscript, template, svg, nav, footer, header, aside').remove();

  const title =
    cleanInline(frontmatter.title) ||
    cleanInline($('meta[property="og:title"]').attr('content')) ||
    cleanInline($('title').first().text()) ||
    cleanInline($('h1').first().text()) ||
    titleFromUrl(source.url);

  const description =
    cleanInline(frontmatter.description) ||
    cleanInline(frontmatter.summary) ||
    cleanInline($('meta[name="description"]').attr('content')) ||
    cleanInline($('meta[property="og:description"]').attr('content')) ||
    firstSemanticParagraph(source, $) ||
    cleanInline($('p').first().text()) ||
    `Information about ${title}.`;

  return {
    url: source.url,
    title,
    description: truncateSentence(description, 220),
    section: classifySection(source.url, source.sourcePath),
    text: cleanBlock($.root().text() || source.raw),
    sourcePath: source.sourcePath,
  };
}

function firstSemanticParagraph(
  source: LlmsSourcePage,
  $: ReturnType<typeof cheerio.load>
): string {
  if (isMarkdownSource(source)) {
    return firstMarkdownParagraph(source.raw) || cleanInline($('p').first().text());
  }

  return cleanInline($('p').first().text());
}

function isMarkdownSource(source: LlmsSourcePage): boolean {
  return /\.(md|markdown|mdx)$/i.test(source.sourcePath ?? '');
}

function parseFrontmatter(raw: string): Frontmatter {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};

  const frontmatter: Frontmatter = {};
  for (const line of match[1].split(/\r?\n/)) {
    const field = line.match(/^([A-Za-z_][\w-]*)\s*:\s*(.+)$/);
    if (!field) continue;

    const key = field[1].toLowerCase();
    const value = field[2].replace(/^['"]|['"]$/g, '').trim();

    if (key === 'title') frontmatter.title = value;
    if (key === 'description') frontmatter.description = value;
    if (key === 'summary') frontmatter.summary = value;
  }

  return frontmatter;
}

function firstMarkdownParagraph(raw: string): string {
  const body = raw.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, '');

  for (const block of body.split(/\r?\n\r?\n/)) {
    const normalized = cleanBlock(block);
    if (!normalized || /^#{1,6}\s/.test(normalized) || /^[-*]\s/.test(normalized)) {
      continue;
    }
    if (/^(import|export)\s/.test(normalized)) continue;
    return truncateSentence(normalized.replace(/\[([^\]]+)\]\([^)]+\)/g, '$1'), 220);
  }

  return '';
}

function classifySection(url: string, sourcePath?: string): string {
  const haystack = `${new URL(url).pathname} ${sourcePath ?? ''}`.toLowerCase();

  if (/(^|\/)(api|reference|sdk|cli)(\/|$)/.test(haystack)) return 'API';
  if (/(^|\/)(docs|documentation|guide|guides|learn)(\/|$)/.test(haystack)) return 'Docs';
  if (/(^|\/)(blog|posts|articles|news)(\/|$)/.test(haystack)) return 'Blog';
  if (/(^|\/)(pricing|features|product|solutions|customers)(\/|$)/.test(haystack)) return 'Product';
  if (/(^|\/)(changelog|releases|legal|privacy|terms|contact)(\/|$)/.test(haystack)) {
    return 'Optional';
  }

  return 'Site';
}

function sectionRank(section: string): number {
  const rank = SECTION_ORDER.indexOf(section);
  return rank === -1 ? SECTION_ORDER.length : rank;
}

function inferSiteName(site: string): string {
  try {
    return new URL(site).hostname.replace(/^www\./, '');
  } catch {
    return 'Website';
  }
}

function titleFromUrl(url: string): string {
  try {
    const pathname = new URL(url).pathname.replace(/\/+$/, '');
    const leaf = pathname.split('/').filter(Boolean).pop() ?? 'Home';
    return leaf
      .replace(/[-_]+/g, ' ')
      .replace(/\b\w/g, (letter) => letter.toUpperCase());
  } catch {
    return 'Untitled';
  }
}

function cleanInline(value: string | undefined): string {
  return cleanBlock(value ?? '').replace(/\s+([,.;:!?])/g, '$1');
}

function cleanBlock(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

function truncateSentence(value: string, maxLength: number): string {
  const clean = cleanInline(value);
  if (clean.length <= maxLength) return clean;

  const truncated = clean.slice(0, maxLength - 1);
  const sentenceEnd = Math.max(
    truncated.lastIndexOf('.'),
    truncated.lastIndexOf('!'),
    truncated.lastIndexOf('?')
  );

  if (sentenceEnd >= 80) {
    return truncated.slice(0, sentenceEnd + 1);
  }

  const lastSpace = truncated.lastIndexOf(' ');
  return `${truncated.slice(0, Math.max(1, lastSpace))}.`;
}
